name: CICD

on:
  push:
    branches: [ "main", "test-branch" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Print Hello world! (kan vara kvar!)
      run: echo Hello, world!

    # Lägg till installation av tester
    - name: Install dependencies
      run: |
        pip install pytest
        pip install faker

    # Kör generate.py (skapar data.json)
    - name: Run generate.py
      run: python generate.py

    # (senare) Run csvtojson.py här!

    # Kör tester
    - name: Run tests
      run: pytest

    # Bygg sajten
    - name: Copy to dist
      run: |
        mkdir dist
        cp index.html dist/index.html
        cp data.json dist/data.json
        cp script.js dist/script.js

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
