name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: Dependencies.txt

      - name: Run Unit Tests
        run: pytest
      # Placeholder for: create CSV, create JSON, run unit tests
      # (you can insert your pip install and test commands here)
      - name: Copy to dist
        run: |
          mkdir -p dist
          cp index.html dist/
          cp data.json dist/
          cp script.js dist/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: github-pages  # explicitly name it, ensures only one exists

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
